#!/usr/bin/env python
"""
Model Comparison Study: Unified Linear Probe Training + Visualization.
=====================================================================

Trains simple linear probes (CLS and patch-level) on pre-extracted
embeddings from all 4 backbones, using pre-computed ground truth labels
for ReXGroundingCT or TotalSegmentator.

For each (model, probe_type) combination, runs a grid search over
learning rates, selects the best LR by validation AUPRC (both ReX and
TotalSegmentator use multi-label BCE), and saves results.

After all training completes, generates visualization plots.

Output Structure:
  {save_root}/
    {model_key}/
      {probe_type}/
        best_model.pth
        best_metrics.json
        lr_{lr}/
          model.pth
          metrics.json
    figures/
      macro_auprc_bars.png
      per_class_heatmap.png
      grid_search_heatmaps.png
      summary_table.txt

Usage:
  python scripts/run_model_comparison_probes.py \
      --config configs/linear_probe_model_comparison_rex.yaml

  # Run only specific models
  python scripts/run_model_comparison_probes.py \
      --config configs/linear_probe_model_comparison_rex.yaml \
      --models lejepa_0 lejepa_2s

  # Run only specific probe types
  python scripts/run_model_comparison_probes.py \
      --config configs/linear_probe_model_comparison_rex.yaml \
      --probe-types cls
"""

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import roc_auc_score, average_precision_score, accuracy_score
from tqdm import tqdm

# --- PATH HACK ---
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def load_config(path):
    """Load YAML config. Tries OmegaConf first, falls back to PyYAML."""
    try:
        from omegaconf import OmegaConf
        return OmegaConf.load(path)
    except ImportError:
        import yaml
        with open(path, "r") as f:
            return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# Probe Models
# ---------------------------------------------------------------------------

class CLSLinearProbe(nn.Module):
    """Single linear layer on CLS token for slice-level classification."""

    def __init__(self, input_dim, num_classes, task_type="multi_label"):
        super().__init__()
        self.classifier = nn.Linear(input_dim, num_classes)
        self.task_type = task_type

    def forward(self, x):
        """
        Args:
            x: [B, D] CLS token embeddings
        Returns:
            logits: [B, num_classes]
        """
        return self.classifier(x)


class PatchLinearProbe(nn.Module):
    """Single linear layer applied per-patch for patch-level classification."""

    def __init__(self, input_dim, num_classes, task_type="multi_label"):
        super().__init__()
        self.classifier = nn.Linear(input_dim, num_classes)
        self.task_type = task_type

    def forward(self, x):
        """
        Args:
            x: [B, N_patches, D] patch token embeddings
        Returns:
            logits: [B, N_patches, num_classes]
        """
        return self.classifier(x)


# ---------------------------------------------------------------------------
# Data Loading
# ---------------------------------------------------------------------------

def load_embeddings_and_labels(embedding_dir, gt_dir, task, model_key,
                                probe_type, split_file_path, seed=42):
    """
    Load pre-extracted embeddings and ground truth labels using a
    pre-computed patient-level train/val/test split.

    Args:
        embedding_dir: Path to {root}/{model_key}/{method}/ directory
        gt_dir: Path to {root}/{task}/ directory
        task: "rex" or "totalseg"
        model_key: e.g. "lejepa_0"
        probe_type: "cls" or "patch"
        split_file_path: Path to patient_splits.json (generated by
                         extract_model_comparison_groundtruth.py)
        seed: Random seed (unused; split is pre-determined)

    Returns:
        (train_X, train_y, val_X, val_y, test_X, test_y) as numpy arrays
    """
    emb_dir = Path(embedding_dir)
    gt_dir = Path(gt_dir)

    if not emb_dir.is_dir():
        raise FileNotFoundError(f"Embedding directory not found: {emb_dir}")
    if not gt_dir.is_dir():
        raise FileNotFoundError(f"Ground truth directory not found: {gt_dir}")

    # Load patient-level split assignments
    with open(split_file_path, "r") as f:
        split_assignments = json.load(f)

    # Build sets of volume names per split
    train_volumes = set(split_assignments["train"])
    val_volumes = set(split_assignments["val"])
    test_volumes = set(split_assignments["test"])

    # Strip .nii.gz/.npy extensions for matching (embeddings are saved by base name)
    def _base_name(v):
        return v.replace(".nii.gz", "").replace(".npy", "")

    train_bases = {_base_name(v) for v in train_volumes}
    val_bases = {_base_name(v) for v in val_volumes}
    test_bases = {_base_name(v) for v in test_volumes}

    # Find matching files
    emb_files = sorted(emb_dir.glob("*.npz"))
    gt_files = sorted(gt_dir.glob("*.npz"))

    emb_names = {f.stem for f in emb_files}
    # Groundtruth files are named like "valid_1001_a_1.nii.gz.npz",
    # so .stem gives "valid_1001_a_1.nii.gz". Strip .nii.gz to match embeddings.
    gt_names = {f.stem.replace(".nii.gz", "") for f in gt_files}
    common = sorted(emb_names & gt_names)

    if not common:
        raise RuntimeError(
            f"No matching files between {emb_dir} and {gt_dir}"
        )

    # Assign each matching volume to its split
    train_names = [n for n in common if n in train_bases]
    val_names = [n for n in common if n in val_bases]
    test_names = [n for n in common if n in test_bases]

    print(f"Found {len(common)} matching volumes")
    print(f"  Train: {len(train_names)} | Val: {len(val_names)} | Test: {len(test_names)}")

    def _load_split(volume_names, split_label):
        """Load embeddings and labels for a list of volume names."""
        all_X = []
        all_y = []

        for name in tqdm(volume_names, desc=f"Loading {split_label} {probe_type} data"):
            emb_data = np.load(str(emb_dir / f"{name}.npz"))
            # Groundtruth files include .nii.gz in the name: "valid_1001_a_1.nii.gz.npz"
            gt_data = np.load(str(gt_dir / f"{name}.nii.gz.npz"))

            if probe_type == "cls":
                X = emb_data["cls"]  # [D, D_emb]
                y = gt_data["cls_labels"]  # [D] or [D, num_classes]
            else:
                X = emb_data["patch"]  # [D, N, D_emb]
                patch_key = f"patch_labels_{model_key}"
                if patch_key in gt_data:
                    y = gt_data[patch_key]
                else:
                    patch_keys = [k for k in gt_data.keys() if k.startswith("patch_labels")]
                    if patch_keys:
                        y = gt_data[patch_keys[0]]
                    else:
                        continue

            # Flatten slice dimension
            if probe_type == "cls":
                X_flat = X.reshape(-1, X.shape[-1])
                if y.ndim == 1:
                    y_flat = y
                else:
                    y_flat = y.reshape(-1, y.shape[-1])
            else:
                # X: [D, N_patches, D_emb] -> [D * N_patches, D_emb]
                X_flat = X.reshape(-1, X.shape[-1])
                # y: [D, num_classes, grid, grid] -> [D * grid * grid, num_classes]
                if y.ndim == 4:
                    # [D, C, G, G] -> [D, G, G, C] -> [D*G*G, C]
                    y_flat = y.transpose(0, 2, 3, 1).reshape(-1, y.shape[1])
                elif y.ndim == 3:
                    # [D, C, N] -> [D*N, C]
                    y_flat = y.transpose(0, 2, 1).reshape(-1, y.shape[1])
                elif y.ndim == 2:
                    y_flat = y.reshape(-1)
                else:
                    y_flat = y.reshape(-1, y.shape[-1])

            # Validate that X and y have matching row counts
            if X_flat.shape[0] != y_flat.shape[0]:
                print(f"  [WARN] {name}: X rows ({X_flat.shape[0]}) != y rows "
                      f"({y_flat.shape[0]}), skipping")
                continue

            all_X.append(X_flat)
            all_y.append(y_flat)

        if not all_X:
            return np.array([]), np.array([])
        return np.concatenate(all_X, axis=0), np.concatenate(all_y, axis=0)

    train_X, train_y = _load_split(train_names, "train")
    val_X, val_y = _load_split(val_names, "val")
    test_X, test_y = _load_split(test_names, "test")

    print(f"Total samples — Train: {train_X.shape[0]}, Val: {val_X.shape[0]}, Test: {test_X.shape[0]}")

    return train_X, train_y, val_X, val_y, test_X, test_y


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_probe(model, train_X, train_y, val_X, val_y, lr, total_steps,
                eval_freq, batch_size, task_type, device):
    """
    Train a linear probe with SGD and cosine annealing.

    Returns:
        best_val_metric: float (AUPRC for multi_label, accuracy for multi_class)
        best_state_dict: model state dict at best validation metric
    """
    model = model.to(device)

    if task_type == "multi_label":
        criterion = nn.BCEWithLogitsLoss()
        train_y_t = torch.from_numpy(train_y).float()
        val_y_t = torch.from_numpy(val_y).float()
    else:
        criterion = nn.CrossEntropyLoss()
        train_y_t = torch.from_numpy(train_y).long()
        val_y_t = torch.from_numpy(val_y).long()

    train_X_t = torch.from_numpy(train_X).float()
    val_X_t = torch.from_numpy(val_X).float()

    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.95, weight_decay=0)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=total_steps)

    best_val_metric = -1.0
    best_state_dict = {k: v.cpu().clone() for k, v in model.state_dict().items()}

    n_samples = len(train_X_t)

    for step in range(1, total_steps + 1):
        # Sample random batch
        indices = torch.randint(0, n_samples, (batch_size,))
        x_batch = train_X_t[indices].to(device)
        y_batch = train_y_t[indices].to(device)

        optimizer.zero_grad()
        logits = model(x_batch)
        loss = criterion(logits, y_batch)
        loss.backward()
        optimizer.step()
        scheduler.step()

        if step % eval_freq == 0 or step == total_steps:
            val_metric = evaluate_probe(
                model, val_X_t, val_y_t, batch_size, task_type, device
            )
            if val_metric > best_val_metric:
                best_val_metric = val_metric
                best_state_dict = {k: v.cpu().clone() for k, v in model.state_dict().items()}

    return best_val_metric, best_state_dict


@torch.no_grad()
def evaluate_probe(model, X, y, batch_size, task_type, device):
    """Evaluate probe and return the primary metric."""
    model.eval()
    all_probs = []
    n_samples = len(X)

    for i in range(0, n_samples, batch_size):
        x_batch = X[i:i + batch_size].to(device)
        logits = model(x_batch)
        if task_type == "multi_label":
            probs = torch.sigmoid(logits).cpu().numpy()
        else:
            probs = torch.softmax(logits, dim=-1).cpu().numpy()
        all_probs.append(probs)

    probs = np.concatenate(all_probs, axis=0)
    y_np = y.numpy()

    if task_type == "multi_label":
        # Binarize soft labels for sklearn metrics (TotalSegmentator uses
        # fractional coverage labels; BCE loss handles soft labels natively).
        y_bin = (y_np > 0).astype(np.float32)
        try:
            metric = average_precision_score(y_bin, probs, average="macro")
        except ValueError:
            metric = 0.0
    else:
        preds = probs.argmax(axis=1)
        metric = accuracy_score(y_np, preds)

    model.train()
    return metric


@torch.no_grad()
def evaluate_probe_detailed(model, X, y, batch_size, task_type, device,
                             class_names=None, train_y=None, val_y=None,
                             min_positive_samples=5):
    """Evaluate probe and return detailed metrics.

    Args:
        model: The probe model.
        X, y: Evaluation data (test or val).
        batch_size: Batch size for inference.
        task_type: "multi_label" or "multi_class".
        device: Torch device.
        class_names: Optional list of class name strings.
        train_y: Training labels (numpy) for computing prevalence.
        val_y: Validation labels (numpy) for computing prevalence.
        min_positive_samples: Minimum number of positive samples required
            in the evaluation set for a class to be considered "valid"
            for metric reporting. Classes below this threshold get
            metrics set to 0.0 and are flagged as "insufficient_data".

    Returns:
        metrics dict with macro_auroc, macro_auprc, per_class, and
        per_class_prevalence keys.
    """
    model.eval()
    all_probs = []
    n_samples = len(X)

    for i in range(0, n_samples, batch_size):
        x_batch = X[i:i + batch_size].to(device)
        logits = model(x_batch)
        if task_type == "multi_label":
            probs = torch.sigmoid(logits).cpu().numpy()
        else:
            probs = torch.softmax(logits, dim=-1).cpu().numpy()
        all_probs.append(probs)

    probs = np.concatenate(all_probs, axis=0)
    y_np = y.numpy()

    # Binarize soft labels for sklearn metrics (TotalSegmentator uses
    # fractional coverage labels; BCE loss handles soft labels natively).
    if task_type == "multi_label":
        y_eval = (y_np > 0).astype(np.float32)
    else:
        y_eval = y_np

    # --- Compute per-class prevalences ---
    # Prevalence = fraction of samples where the class is present (>0 for
    # multi_label soft labels, >0.5 for binary).
    def _compute_prevalence(labels, num_classes):
        """Compute per-class positive rate from a label matrix."""
        if labels is None or len(labels) == 0:
            return None
        if labels.ndim == 1:
            # Multi-class: count per class
            counts = np.bincount(labels.astype(int), minlength=num_classes)
            return (counts / len(labels)).tolist()
        else:
            # Multi-label: fraction of samples with >0 for each class
            binary = (labels > 0).astype(np.float32)
            return binary.mean(axis=0).tolist()

    num_classes = y_eval.shape[1] if y_eval.ndim > 1 else int(y_eval.max()) + 1
    train_prev = _compute_prevalence(train_y, num_classes)
    val_prev = _compute_prevalence(val_y, num_classes)
    eval_prev = _compute_prevalence(y_np, num_classes)

    # --- Determine which classes have sufficient data ---
    # A class is "valid" if it has >= min_positive_samples positive examples
    # in the evaluation set.
    if y_eval.ndim > 1:
        eval_pos_counts = (y_eval > 0).sum(axis=0)
    else:
        eval_pos_counts = np.bincount(y_eval.astype(int), minlength=num_classes)
    valid_classes = eval_pos_counts >= min_positive_samples

    metrics = {}

    if task_type == "multi_label":
        # --- Filtered macro metrics (only valid classes) ---
        valid_indices = np.where(valid_classes)[0]
        if len(valid_indices) > 0:
            y_valid = y_eval[:, valid_indices]
            p_valid = probs[:, valid_indices]
            try:
                per_class_auroc = roc_auc_score(y_valid, p_valid, average=None)
                metrics["macro_auroc"] = float(np.nanmean(per_class_auroc))
            except ValueError:
                metrics["macro_auroc"] = 0.0
            try:
                metrics["macro_auprc"] = float(average_precision_score(y_valid, p_valid, average="macro"))
            except ValueError:
                metrics["macro_auprc"] = 0.0
            metrics["n_valid_classes"] = int(len(valid_indices))
            metrics["n_total_classes"] = int(num_classes)
            metrics["n_skipped_classes"] = int(num_classes - len(valid_indices))
        else:
            metrics["macro_auroc"] = 0.0
            metrics["macro_auprc"] = 0.0
            metrics["n_valid_classes"] = 0
            metrics["n_total_classes"] = int(num_classes)
            metrics["n_skipped_classes"] = int(num_classes)

        # --- Also compute original (unfiltered) macro for reference ---
        try:
            per_class_auroc_all = roc_auc_score(y_eval, probs, average=None)
            metrics["macro_auroc_unfiltered"] = float(np.nanmean(per_class_auroc_all))
        except ValueError:
            metrics["macro_auroc_unfiltered"] = 0.0
        try:
            metrics["macro_auprc_unfiltered"] = float(average_precision_score(y_eval, probs, average="macro"))
        except ValueError:
            metrics["macro_auprc_unfiltered"] = 0.0

        # Per-class metrics with prevalence and validity flag
        if class_names:
            per_class = {}
            for i, name in enumerate(class_names):
                if i >= y_eval.shape[1]:
                    break
                y_t = y_eval[:, i]
                y_p = probs[:, i]

                entry = {
                    "train_prevalence": train_prev[i] if train_prev else None,
                    "val_prevalence": val_prev[i] if val_prev else None,
                    "eval_prevalence": eval_prev[i] if eval_prev else None,
                    "eval_positive_count": int(eval_pos_counts[i]),
                    "sufficient_data": bool(valid_classes[i]),
                }

                if not valid_classes[i]:
                    entry["auroc"] = 0.0
                    entry["auprc"] = 0.0
                    entry["skipped_reason"] = (
                        f"Only {int(eval_pos_counts[i])} positive samples "
                        f"(need >= {min_positive_samples})"
                    )
                elif len(np.unique(y_t)) < 2:
                    entry["auroc"] = 0.0
                    entry["auprc"] = 0.0
                else:
                    entry["auroc"] = float(roc_auc_score(y_t, y_p))
                    entry["auprc"] = float(average_precision_score(y_t, y_p))

                per_class[name] = entry
            metrics["per_class"] = per_class
    else:
        preds = probs.argmax(axis=1)
        metrics["accuracy"] = float(accuracy_score(y_np, preds))

        # Per-class accuracy with prevalence
        if class_names:
            per_class = {}
            for i, name in enumerate(class_names):
                if i >= probs.shape[1]:
                    break
                mask = y_np == i
                entry = {
                    "train_prevalence": train_prev[i] if train_prev else None,
                    "val_prevalence": val_prev[i] if val_prev else None,
                    "eval_prevalence": eval_prev[i] if eval_prev else None,
                    "eval_count": int(mask.sum()),
                    "sufficient_data": bool(valid_classes[i]),
                }
                if mask.sum() > 0:
                    entry["accuracy"] = float((preds[mask] == i).mean())
                else:
                    entry["accuracy"] = 0.0
                per_class[name] = entry
            metrics["per_class"] = per_class

    model.train()
    return metrics


# ---------------------------------------------------------------------------
# Grid Search
# ---------------------------------------------------------------------------

def run_grid_search(model_key, probe_type, config, device):
    """
    Run grid search over learning rates for a single (model, probe_type).

    Uses patient-level train/val/test split. Grid search selects best LR
    on validation set, then evaluates on test set for final reporting.

    Returns:
        results dict with best_lr, best_val_metric, test_metrics, etc.
    """
    exp_cfg = config["experiment"]
    emb_cfg = config["embeddings"]
    gt_cfg = config["groundtruth"]
    task = config["task"]
    task_type = config["task_type"]
    num_classes = config["num_classes"]

    embedding_dir = os.path.join(emb_cfg["root"], model_key, emb_cfg["method"])
    gt_dir = os.path.join(gt_cfg["root"], gt_cfg["task"])
    split_file = os.path.join(gt_cfg["root"], gt_cfg.get("split_file", "patient_splits.json"))

    if not os.path.exists(split_file):
        raise FileNotFoundError(
            f"Patient split file not found: {split_file}. "
            f"Run extract_model_comparison_groundtruth.py first."
        )

    print(f"\n{'=' * 60}")
    print(f"Model: {model_key} | Probe: {probe_type} | Task: {task}")
    print(f"{'=' * 60}")

    # Load data with patient-level splits
    train_X, train_y, val_X, val_y, test_X, test_y = load_embeddings_and_labels(
        embedding_dir, gt_dir, task, model_key, probe_type,
        split_file_path=split_file,
        seed=exp_cfg["seed"]
    )

    # Grid search over LRs using validation set
    best_lr = None
    best_val_metric = -1.0
    best_state_dict = None
    lr_results = {}

    for lr in exp_cfg["learning_rates"]:
        print(f"\n  LR={lr}...")

        if probe_type == "cls":
            model = CLSLinearProbe(exp_cfg["input_dim"], num_classes, task_type)
        else:
            model = PatchLinearProbe(exp_cfg["input_dim"], num_classes, task_type)

        val_metric, state_dict = train_probe(
            model, train_X, train_y, val_X, val_y,
            lr=lr,
            total_steps=exp_cfg["total_steps"],
            eval_freq=exp_cfg["eval_freq"],
            batch_size=exp_cfg["batch_size"],
            task_type=task_type,
            device=device,
        )

        lr_results[str(lr)] = {"val_metric": float(val_metric)}
        print(f"    Val metric: {val_metric:.4f}")

        if val_metric > best_val_metric:
            best_val_metric = val_metric
            best_lr = lr
            best_state_dict = state_dict

    # Save best model
    save_dir = os.path.join(exp_cfg["save_root"], model_key, probe_type)
    os.makedirs(save_dir, exist_ok=True)

    best_model_path = os.path.join(save_dir, "best_model.pth")
    torch.save(best_state_dict, best_model_path)

    # Evaluate best model on validation set with detailed metrics
    if probe_type == "cls":
        best_model = CLSLinearProbe(exp_cfg["input_dim"], num_classes, task_type)
    else:
        best_model = PatchLinearProbe(exp_cfg["input_dim"], num_classes, task_type)
    best_model.load_state_dict(best_state_dict)
    best_model = best_model.to(device)

    val_X_t = torch.from_numpy(val_X).float()
    if task_type == "multi_label":
        val_y_t = torch.from_numpy(val_y).float()
    else:
        val_y_t = torch.from_numpy(val_y).long()

    # Resolve class names: rex_classes for ReX, ts_classes for TotalSegmentator
    class_names = config.get("rex_classes", None) or config.get("ts_classes", None)
    min_pos = exp_cfg.get("min_positive_samples", 5)
    val_detailed = evaluate_probe_detailed(
        best_model, val_X_t, val_y_t,
        batch_size=exp_cfg["batch_size"],
        task_type=task_type,
        device=device,
        class_names=class_names,
        train_y=train_y,
        val_y=val_y,
        min_positive_samples=min_pos,
    )

    # --- Evaluate on test set ---
    test_metrics = {}
    if len(test_X) > 0:
        test_X_t = torch.from_numpy(test_X).float()
        if task_type == "multi_label":
            test_y_t = torch.from_numpy(test_y).float()
        else:
            test_y_t = torch.from_numpy(test_y).long()

        test_metrics = evaluate_probe_detailed(
            best_model, test_X_t, test_y_t,
            batch_size=exp_cfg["batch_size"],
            task_type=task_type,
            device=device,
            class_names=class_names,
            train_y=train_y,
            val_y=val_y,
            min_positive_samples=min_pos,
        )
        print(f"  Test metrics: { {k: v for k, v in test_metrics.items() if k != 'per_class'} }")

    results = {
        "model": model_key,
        "probe_type": probe_type,
        "task": task,
        "best_lr": best_lr,
        "best_val_metric": float(best_val_metric),
        "lr_results": lr_results,
        "val_detailed_metrics": val_detailed,
        "test_metrics": test_metrics,
        "n_train": int(len(train_X)),
        "n_val": int(len(val_X)),
        "n_test": int(len(test_X)),
    }

    # Save results JSON
    results_path = os.path.join(save_dir, "best_metrics.json")
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2, default=str)

    print(f"\n  Best LR: {best_lr}, Best val metric: {best_val_metric:.4f}")
    print(f"  Saved to: {save_dir}")

    return results


# ---------------------------------------------------------------------------
# Consolidated Results Export
# ---------------------------------------------------------------------------

def save_consolidated_results(all_results, config):
    """
    Save a flat, human-readable JSON with per-class and macro results
    for all (model, probe_type) combinations. This is the primary output
    file for downstream analysis and paper tables.

    Now includes per-class prevalence (train/val/test) and flags for
    classes with insufficient data.
    """
    exp_cfg = config["experiment"]
    task = config["task"]
    task_type = config["task_type"]
    # Resolve class names: rex_classes for ReX, ts_classes for TotalSegmentator
    class_names = config.get("rex_classes", None) or config.get("ts_classes", None)
    min_pos = exp_cfg.get("min_positive_samples", 5)

    save_root = exp_cfg["save_root"]
    os.makedirs(save_root, exist_ok=True)

    # Build a flat list of result entries
    entries = []
    for r in all_results:
        model_key = r["model"]
        probe_type = r["probe_type"]

        # Extract test metrics (preferred) or val metrics
        test_m = r.get("test_metrics", {})
        val_m = r.get("val_detailed_metrics", {})

        entry = {
            "model": model_key,
            "probe_type": probe_type,
            "task": task,
            "task_type": task_type,
            "best_lr": r["best_lr"],
            "best_val_metric": r["best_val_metric"],
            "n_train": r.get("n_train", 0),
            "n_val": r.get("n_val", 0),
            "n_test": r.get("n_test", 0),
            "min_positive_samples": min_pos,
        }

        if task_type == "multi_label":
            entry["test_macro_auroc"] = test_m.get("macro_auroc", None)
            entry["test_macro_auprc"] = test_m.get("macro_auprc", None)
            entry["test_macro_auroc_unfiltered"] = test_m.get("macro_auroc_unfiltered", None)
            entry["test_macro_auprc_unfiltered"] = test_m.get("macro_auprc_unfiltered", None)
            entry["test_n_valid_classes"] = test_m.get("n_valid_classes", None)
            entry["test_n_total_classes"] = test_m.get("n_total_classes", None)
            entry["test_n_skipped_classes"] = test_m.get("n_skipped_classes", None)
            entry["val_macro_auroc"] = val_m.get("macro_auroc", None)
            entry["val_macro_auprc"] = val_m.get("macro_auprc", None)
            entry["val_macro_auroc_unfiltered"] = val_m.get("macro_auroc_unfiltered", None)
            entry["val_macro_auprc_unfiltered"] = val_m.get("macro_auprc_unfiltered", None)
            entry["val_n_valid_classes"] = val_m.get("n_valid_classes", None)
            entry["val_n_total_classes"] = val_m.get("n_total_classes", None)
            entry["val_n_skipped_classes"] = val_m.get("n_skipped_classes", None)

            # Per-class metrics with prevalence (test preferred, fall back to val)
            test_per_class = test_m.get("per_class", {})
            val_per_class = val_m.get("per_class", {})
            per_class = {}
            if class_names:
                for cls_name in class_names:
                    tc = test_per_class.get(cls_name, {})
                    vc = val_per_class.get(cls_name, {})
                    # Use test if available, else val
                    source = tc if tc else vc
                    per_class[cls_name] = {
                        "test_auroc": tc.get("auroc", None),
                        "test_auprc": tc.get("auprc", None),
                        "val_auroc": vc.get("auroc", None),
                        "val_auprc": vc.get("auprc", None),
                        "train_prevalence": source.get("train_prevalence", None),
                        "val_prevalence": source.get("val_prevalence", None),
                        "test_prevalence": source.get("eval_prevalence", None),
                        "test_positive_count": source.get("eval_positive_count", None),
                        "sufficient_data": source.get("sufficient_data", None),
                        "skipped_reason": source.get("skipped_reason", None),
                    }
            else:
                # Fallback: use whatever keys are in per_class
                source = test_per_class if test_per_class else val_per_class
                for cls_name, metrics in source.items():
                    tc = test_per_class.get(cls_name, {})
                    vc = val_per_class.get(cls_name, {})
                    per_class[cls_name] = {
                        "test_auroc": tc.get("auroc", None),
                        "test_auprc": tc.get("auprc", None),
                        "val_auroc": vc.get("auroc", None),
                        "val_auprc": vc.get("auprc", None),
                        "train_prevalence": metrics.get("train_prevalence", None),
                        "val_prevalence": metrics.get("val_prevalence", None),
                        "test_prevalence": metrics.get("eval_prevalence", None),
                        "test_positive_count": metrics.get("eval_positive_count", None),
                        "sufficient_data": metrics.get("sufficient_data", None),
                        "skipped_reason": metrics.get("skipped_reason", None),
                    }
            entry["per_class"] = per_class
        else:
            entry["test_accuracy"] = test_m.get("accuracy", None)
            entry["val_accuracy"] = val_m.get("accuracy", None)

        entries.append(entry)

    # Save consolidated JSON
    consolidated = {
        "task": task,
        "task_type": task_type,
        "num_classes": config.get("num_classes", None),
        "embedding_method": config["embeddings"]["method"],
        "min_positive_samples": min_pos,
        "results": entries,
    }

    output_path = os.path.join(save_root, "consolidated_results.json")
    with open(output_path, "w") as f:
        json.dump(consolidated, f, indent=2, default=str)
    print(f"\n✅ Consolidated results saved to: {output_path}")


# ---------------------------------------------------------------------------
# Visualization
# ---------------------------------------------------------------------------

def generate_visualizations(all_results, config):
    """Generate summary plots from all results."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.ticker as mticker
    except ImportError:
        print("\n⚠️  matplotlib not installed. Skipping plots.")
        return

    exp_cfg = config["experiment"]
    save_root = exp_cfg["save_root"]
    figures_dir = os.path.join(save_root, "figures")
    os.makedirs(figures_dir, exist_ok=True)

    task = config["task"]
    task_type = config["task_type"]
    metric_name = "AUPRC" if task_type == "multi_label" else "Accuracy"

    # Collect data — prefer test metrics, fall back to val metrics
    def _get_primary_metric(r):
        """Get the primary metric from test set if available, else val."""
        test_m = r.get("test_metrics", {})
        if test_m:
            if task_type == "multi_label":
                return test_m.get("macro_auprc", r["best_val_metric"])
            else:
                return test_m.get("accuracy", r["best_val_metric"])
        return r["best_val_metric"]

    # Build per-model metrics dict (handles missing probe types gracefully)
    model_metrics = {}
    for r in all_results:
        m = r["model"]
        if m not in model_metrics:
            model_metrics[m] = {"cls": None, "patch": None}
        model_metrics[m][r["probe_type"]] = _get_primary_metric(r)

    unique_models = list(model_metrics.keys())
    cls_metrics = [model_metrics[m]["cls"] or 0.0 for m in unique_models]
    patch_metrics = [model_metrics[m]["patch"] or 0.0 for m in unique_models]

    # --- Plot 1: Grouped bar chart comparing models ---
    fig, ax = plt.subplots(figsize=(10, 6))
    x = np.arange(len(unique_models))
    width = 0.35

    bars1 = ax.bar(x - width/2, cls_metrics, width, label="CLS Probe",
                   color="#2196F3", edgecolor="white")
    bars2 = ax.bar(x + width/2, patch_metrics, width, label="Patch Probe",
                   color="#FF9800", edgecolor="white")

    for bar, val in zip(bars1, cls_metrics):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                f"{val:.4f}", ha="center", va="bottom", fontsize=9)
    for bar, val in zip(bars2, patch_metrics):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                f"{val:.4f}", ha="center", va="bottom", fontsize=9)

    ax.set_xticks(x)
    ax.set_xticklabels([m.replace("_", "-").upper() for m in unique_models], fontsize=11)
    ax.set_ylabel(f"Test {metric_name}")
    ax.set_title(f"Model Comparison Study: {task.upper()} — Test {metric_name} by Model and Probe Type")
    ax.legend(fontsize=10)
    all_metrics = [v for v in cls_metrics + patch_metrics if v is not None]
    if all_metrics:
        ax.set_ylim(0, max(all_metrics) * 1.15 + 0.05)
    ax.grid(axis="y", alpha=0.3)
    plt.tight_layout()

    path = os.path.join(figures_dir,f"{task}_comparison_bars.png")
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  ✅ Saved: {path}")

    # --- Plot 2: Grid search heatmaps ---
    lrs = [str(lr) for lr in exp_cfg["learning_rates"]]
    probe_types = ["cls", "patch"]

    for probe_type in probe_types:
        matrix = []
        for r in all_results:
            if r["probe_type"] == probe_type:
                row = []
                for lr in lrs:
                    row.append(r["lr_results"].get(lr, {}).get("val_metric", 0.0))
                matrix.append(row)

        if not matrix:
            continue

        matrix = np.array(matrix)
        model_labels = [r["model"] for r in all_results if r["probe_type"] == probe_type]

        fig, ax = plt.subplots(figsize=(max(6, len(lrs) * 1.2),
                                        max(3, len(model_labels) * 0.8)))
        im = ax.imshow(matrix, aspect="auto", cmap="YlOrRd", vmin=0.0)

        ax.set_xticks(range(len(lrs)))
        ax.set_xticklabels(lrs, fontsize=9)
        ax.set_yticks(range(len(model_labels)))
        ax.set_yticklabels([m.replace("_", "-").upper() for m in model_labels], fontsize=9)
        ax.set_xlabel("Learning Rate")
        ax.set_ylabel("Model")

        for i in range(len(model_labels)):
            for j in range(len(lrs)):
                val = matrix[i, j]
                if val > 0:
                    text_color = "white" if val < 0.5 else "black"
                    ax.text(j, i, f"{val:.4f}", ha="center", va="center",
                            fontsize=8, color=text_color, fontweight="bold")

        cbar = fig.colorbar(im, ax=ax, shrink=0.8)
        cbar.set_label(f"Val {metric_name}")
        ax.set_title(f"Grid Search — {probe_type.upper()} Probe ({task.upper()})")
        plt.tight_layout()

        path = os.path.join(figures_dir,f"{task}_{probe_type}_grid_search.png")
        fig.savefig(path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        print(f"  ✅ Saved: {path}")

    # --- Plot 3: Per-class AUPRC heatmap (multi-label tasks, from test set) ---
    # Resolve class names for both ReX and TotalSegmentator
    plot_class_names = config.get("rex_classes", None) or config.get("ts_classes", None)
    if task_type == "multi_label" and plot_class_names:
        for probe_type in probe_types:
            matrix = []
            model_labels = []
            # Collect prevalence info from first model's test metrics
            prevalence_info = None
            for r in all_results:
                if r["probe_type"] == probe_type:
                    model_labels.append(r["model"])
                    # Prefer test per-class metrics, fall back to val
                    test_m = r.get("test_metrics", {})
                    per_class = test_m.get("per_class", {}) if test_m else {}
                    if not per_class:
                        per_class = r.get("val_detailed_metrics", {}).get("per_class", {})
                    if prevalence_info is None:
                        prevalence_info = per_class
                    row = []
                    for cls_name in plot_class_names:
                        row.append(per_class.get(cls_name, {}).get("auprc", 0.0))
                    matrix.append(row)

            if not matrix:
                continue

            matrix = np.array(matrix)

            # Build x-tick labels with prevalence annotation
            x_labels = []
            for j, cls_name in enumerate(plot_class_names):
                if prevalence_info and cls_name in prevalence_info:
                    prev = prevalence_info[cls_name].get("eval_prevalence", None)
                    if prev is not None and prev > 0:
                        x_labels.append(f"{cls_name}\n({prev:.1%})")
                    else:
                        x_labels.append(f"{cls_name}\n(0%)")
                else:
                    x_labels.append(cls_name)

            fig, ax = plt.subplots(figsize=(max(16, len(plot_class_names) * 1.0),
                                             max(5, len(model_labels) * 0.7)))
            im = ax.imshow(matrix, aspect="auto", cmap="YlOrRd", vmin=0.0, vmax=1.0)

            ax.set_xticks(range(len(plot_class_names)))
            ax.set_xticklabels(x_labels, rotation=45, ha="right", fontsize=7)
            ax.set_yticks(range(len(model_labels)))
            ax.set_yticklabels([m.replace("_", "-").upper() for m in model_labels], fontsize=9)

            for i in range(len(model_labels)):
                for j in range(len(plot_class_names)):
                    val = matrix[i, j]
                    if val > 0:
                        text_color = "white" if val < 0.55 else "black"
                        ax.text(j, i, f"{val:.3f}", ha="center", va="center",
                                fontsize=7, color=text_color, fontweight="bold")

            cbar = fig.colorbar(im, ax=ax, shrink=0.8)
            cbar.set_label("AUPRC")
            ax.set_title(f"Test Per-Class AUPRC (with prevalence) — {probe_type.upper()} Probe ({task.upper()})")
            plt.tight_layout()

            path = os.path.join(figures_dir,f"{task}_{probe_type}_per_class_heatmap.png")
            fig.savefig(path, dpi=150, bbox_inches="tight")
            plt.close(fig)
            print(f"  ✅ Saved: {path}")

    # --- Write summary table ---
    summary_path = os.path.join(figures_dir,"summary_table.txt")
    with open(summary_path, "w") as f:
        f.write(f"MODEL COMPARISON STUDY SUMMARY — {task.upper()}\n")
        f.write("=" * 120 + "\n")
        if task_type == "multi_label":
            header = (f"{'Model':<20} {'Probe':<8} {'Best LR':<10} "
                      f"{'Val AUPRC':<12} {'Test AUPRC':<12} "
                      f"{'Valid/Total':<14} {'Skipped':<10}")
        else:
            header = (f"{'Model':<20} {'Probe':<8} {'Best LR':<10} "
                      f"{'Val Acc':<12} {'Test Acc':<12}")
        f.write(header + "\n")
        f.write("-" * 120 + "\n")
        for r in sorted(all_results, key=lambda x: _get_primary_metric(x), reverse=True):
            test_m = r.get("test_metrics", {})
            if task_type == "multi_label":
                test_val = test_m.get("macro_auprc", 0.0)
                n_valid = test_m.get("n_valid_classes", "?")
                n_total = test_m.get("n_total_classes", "?")
                n_skip = test_m.get("n_skipped_classes", "?")
                f.write(
                    f"{r['model']:<20} {r['probe_type']:<8} "
                    f"{str(r['best_lr']):<10} {r['best_val_metric']:<12.4f} "
                    f"{test_val:<12.4f} {n_valid}/{n_total:<11} {n_skip:<10}\n"
                )
            else:
                test_val = test_m.get("accuracy", 0.0)
                f.write(
                    f"{r['model']:<20} {r['probe_type']:<8} "
                    f"{str(r['best_lr']):<10} {r['best_val_metric']:<12.4f} {test_val:<12.4f}\n"
                )
        f.write("=" * 120 + "\n")

        # Add per-class prevalence summary
        if task_type == "multi_label" and plot_class_names:
            f.write("\nPER-CLASS PREVALENCE (from first model's test set)\n")
            f.write("-" * 80 + "\n")
            f.write(f"{'Class':<25} {'Train Prev':<14} {'Val Prev':<14} {'Test Prev':<14} {'#Pos':<8} {'Valid':<8}\n")
            f.write("-" * 80 + "\n")
            # Get prevalence from first result's test metrics
            first_test_m = all_results[0].get("test_metrics", {})
            first_per_class = first_test_m.get("per_class", {})
            for cls_name in plot_class_names:
                info = first_per_class.get(cls_name, {})
                train_p = info.get("train_prevalence")
                val_p = info.get("val_prevalence")
                test_p = info.get("eval_prevalence")
                n_pos = info.get("eval_positive_count", 0)
                valid = "Yes" if info.get("sufficient_data") else "No"
                f.write(
                    f"{cls_name:<25} "
                    f"{train_p if train_p is not None else 'N/A':<14} "
                    f"{val_p if val_p is not None else 'N/A':<14} "
                    f"{test_p if test_p is not None else 'N/A':<14} "
                    f"{n_pos:<8} {valid:<8}\n"
                )
            f.write("-" * 80 + "\n")
    print(f"  ✅ Saved: {summary_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Run model comparison study: linear probe training + visualization"
    )
    parser.add_argument(
        "--config", type=str, required=True,
        help="Path to linear_probe_model_comparison_{rex,ts}.yaml"
    )
    parser.add_argument(
        "--models", type=str, nargs="*", default=None,
        help="Specific models to run (default: all from config)"
    )
    parser.add_argument(
        "--probe-types", type=str, nargs="*", default=None,
        choices=["cls", "patch"],
        help="Specific probe types to run (default: all from config)"
    )
    parser.add_argument(
        "--skip-existing", action="store_true",
        help="Skip models that already have results"
    )
    args = parser.parse_args()

    config = load_config(args.config)
    exp_cfg = config["experiment"]
    emb_cfg = config["embeddings"]

    models = args.models if args.models else emb_cfg["models"]
    probe_types = args.probe_types if args.probe_types else exp_cfg["probe_types"]

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")
    print(f"Task: {config['task']}")
    print(f"Models: {models}")
    print(f"Probe types: {probe_types}")
    print(f"Learning rates: {exp_cfg['learning_rates']}")

    all_results = []

    for model_key in models:
        for probe_type in probe_types:
            # Check if already done
            save_dir = os.path.join(exp_cfg["save_root"], model_key, probe_type)
            results_path = os.path.join(save_dir, "best_metrics.json")

            if args.skip_existing and os.path.exists(results_path):
                print(f"\n[SKIP] {model_key}/{probe_type} — already has results")
                with open(results_path, "r") as f:
                    all_results.append(json.load(f))
                continue

            try:
                result = run_grid_search(model_key, probe_type, config, device)
                all_results.append(result)
            except Exception as e:
                print(f"\n[ERROR] {model_key}/{probe_type}: {e}")
                import traceback
                traceback.print_exc()

    # --- Save consolidated results JSON ---
    if all_results:
        save_consolidated_results(all_results, config)

    # --- Generate visualizations ---
    if all_results:
        print("\n" + "=" * 60)
        print("Generating visualizations...")
        print("=" * 60)
        generate_visualizations(all_results, config)

    # --- Print summary ---
    print("\n" + "=" * 100)
    print("MODEL COMPARISON STUDY SUMMARY")
    print("=" * 100)
    metric_name = "AUPRC" if config["task_type"] == "multi_label" else "Accuracy"
    header = f"{'Model':<20} {'Probe':<8} {'Best LR':<10} {'Val ' + metric_name:<14} {'Test ' + metric_name:<14}"
    print(header)
    print("-" * 100)
    for r in sorted(all_results, key=lambda x: (
        x.get("test_metrics", {}).get("macro_auprc", 0.0)
        if config["task_type"] == "multi_label"
        else x.get("test_metrics", {}).get("accuracy", 0.0)
    ), reverse=True):
        test_m = r.get("test_metrics", {})
        if config["task_type"] == "multi_label":
            test_val = test_m.get("macro_auprc", 0.0)
        else:
            test_val = test_m.get("accuracy", 0.0)
        print(
            f"{r['model']:<20} {r['probe_type']:<8} "
            f"{str(r['best_lr']):<10} {r['best_val_metric']:<14.4f} {test_val:<14.4f}"
        )
    print("=" * 100)


if __name__ == "__main__":
    main()
